### ISSUE TITLE
Don't allow to start as root by default.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipykernel#100]
Pendant of https://github.com/jupyter/notebook/issues/1074 on IPython kernel side.

Should we allow starting the kernel as root without a flag ?
I think it is less problematic for the kernel as if the server is not root, you likely cannot start a kernel as root. 
Maybe at least emit a warning ? Or not worth at all ?

**Comment by minrk** [comment]
Unlike the notebook, I don't think it makes sense to prevent the kernel starting as root. It's too hard to get the reason why it refused to start to the user, and too hard for the user to express "yes, this is really what I meant". Plus, the kernel user really should always be the same user as the notebook server, since it really is a multi-process single-user local application.

**Comment by takluyver** [comment]
Yep, and it's quite reasonable to imagine running e.g. `jupyter console` as root. I don't think we need to do anything on the kernel side, though I think it's probably reasonable to have some kind of safeguard for the notebook server.

**Comment by Carreau** [comment]
Fair enough, closing.
