### ISSUE TITLE
Latest version break IPyWidgets

### ISSUE THREAD

**Issue by DonJayamanne** [ipython/ipykernel#1050]
IPyKernel Version: 6.19.0
Install Jupyter and ipywidgets 
Run a notebook with the following code

```python
import ipywidgets as widgets
widgets.IntSlider()
```

Slider is not renderered
Here is the error message
```
A Jupyter widget could not be displayed because the widget state could not be found. 
This could happen if the kernel storing the widget is no longer available, or if the widget state was not saved in the notebook. 
You may be able to create the widget by running the appropriate cells.
```

**Comment by maartenbreddels** [comment]
I tried reproducing this, but I cannot. I did:
```
python -m venv clean-env 
source clean-env/bin/activate
pip install ipywidgets notebook jupyterlab
```
Confirmed I had ipykernel 6.19.0 and ran your code snippet in lab and classic notebook, and it works.

**Comment by martinRenou** [comment]
I can reproduce in JupyterLab. It seems that it fails to open the comm.

**Comment by maartenbreddels** [comment]
Yes, I do too. The reason it worked for me, is because I had my notebook in the ipykernel git root directory, so that the Python runtime picked up the ipykernel git branch I was in, which was 5f429995a38f8dbbd48f18b4aaf284558657e2e2 (the state of branch #1049 before I pushed).
I'll check which commit broke it.

**Comment by maartenbreddels** [comment]
Seems fee98e57ae3024cfb566807fb742cee83af22a18 is the issue. I'll make a fix.
