### ISSUE TITLE
InterruptReply missing status and error properties

### ISSUE THREAD

**Issue by garlandz-db** [ipython/ipykernel#1100]
According to the jupyter [messaging docs](https://jupyter-client.readthedocs.io/en/stable/messaging.html#kernel-interrupt), we should be passing a `status` field in the content of the `InterruptReply` message. However in the[ implementation](https://github.com/ipython/ipykernel/blob/0f09aa690d1881ab6a2b92119215d8561d344e67/ipykernel/kernelbase.py#L908), we are just forwarding the request content (empty) back into the reply. As such, the reply has no information on `status` and the error properties in case the interrupt is not successful.

My suggestion on the fix should be a try catch around the `send_interrupt_children` and return a `{ 'status' : 'ok' }` if no catch occurs and otherwise `{ 'status': 'error', ... }`.

**Comment by blink1073** [comment]
Good catch!  Would you like to submit a PR?

**Comment by jasongrout-db** [comment]
It would be good to add a check in the tests at 

https://github.com/ipython/ipykernel/blob/ea33a31ca48fa13d73b44837b6791aded1fe4858/ipykernel/tests/test_kernel_direct.py#L71-L73 

https://github.com/ipython/ipykernel/blob/ea33a31ca48fa13d73b44837b6791aded1fe4858/ipykernel/tests/test_ipkernel_direct.py#L92-L94

 (and to change those tests to send the interrupt request on the control channel instead of the shell channel).

**Comment by garlandz-db** [comment]
i can get a PR in next week @blink1073.

**Comment by blink1073** [comment]
Great, thanks!

**Comment by garlandz-db** [comment]
any idea where i can get the traceback?

**Comment by blink1073** [comment]
I would set a debug point in the tests and inspect the `reply`.
