### ISSUE TITLE
Filenames conflict with IPython kernel

### ISSUE THREAD

**Issue by nkawasg** [ipython/ipykernel#112]
Two days ago, I made a remark in #40, because I had the same error message. However, that issue is already closed, so I'm opening a new one.

`Error while finding spec for 'ipykernel.__main__' (<class 'ImportError'>: cannot import name 'decorator'); 'ipykernel' is a package and cannot be directly executed`

The problem arises if there's a file called `decorator.py` in the **same folder** you run `jupyter notebook`.

Here are the steps to reproduce the issue.
1. `$ mkdir bugtest`
2. `$ cd bugtest`
3. `$ touch decorator.py`
4. `$ jupyter notebook`
5. Using the GUI, create a new IPython notebook.
6. Go to the terminal. Now, the kernel should restart.

I also tried with several other filenames. I detected that with `argparse.py`, the kernel would also have some problems to start. That being the case, I think the kernel is erroneously trying to import modules.

**Comment by takluyver** [comment]
> I think the kernel is erroneously trying to import modules.

Well, it's certainly trying to import modules. But that's not really erroneous - it's Python code, it can't do much without importing modules.

We've discussed this before. There is a potential way to avoid it: you can start the kernel with a different working directory, passing it the real working directory in some way, and then have it change to that directory once it's finished starting up. However, it would be a bit tricky to do that now that there are multiple different kernels, none of which currently support such a thing. And since it's generally considered a bad idea to give Python files the same name as common modules, we decided not to implement that for the time being.

**Comment by nkawasg** [comment]
I understand, @takluyver. I found this by accident because I was learning about decorators in Python with examples, using a file called `decorator.py`. But you're definitely right; I'll just rename my file. :relieved:

Thank you for your prompt reply.
