### ISSUE TITLE
Empty session keys

### ISSUE THREAD

**Issue by rkern** [ipython/ipykernel#130]
In a couple of places, the inprocess kernel code creates `Session` objects with empty keys. These cause a warning in the `Session` constructor now: https://github.com/jupyter/jupyter_client/pull/106

If an empty key is a valid use-case, then https://github.com/jupyter/jupyter_client/pull/106 needs to be rethought. Otherwise, the inprocess kernel code could use a constant non-empty default key, maybe `b'inprocess'`.

**Comment by takluyver** [comment]
An empty key is OK for inprocess, because you don't need to validate messages when they can't come from anyone else. However, inprocess is a weird corner case that we kind of wish hadn't been created.

**Comment by rkern** [comment]
So what would you like to do? Revert jupyter/jupyter_client#106 and put the warning in another place? Or use a non-empty dummy key for the inprocess kernel?

**Comment by takluyver** [comment]
Does using a dummy key work for inprocess?

**Comment by rkern** [comment]
It's already using a dummy, just one that triggers warnings elsewhere.

**Comment by takluyver** [comment]
An empty key has a special meaning, though - it disables message signing. That's why it raises a warning. It's handy for early development of a kernel, to get other stuff working before you worry about message signing, but we found one kernel was configuring an empty key on installation rather than implementing message signing, so we added the warning to make it clear that that's not the right solution.

**Comment by rkern** [comment]
Well, using a non-empty dummy key appears to work fine. If you'd like to continue to disable the message-signing for in-process kernels, then the warning should be moved to a place where it will not get triggered by legitimate uses.

**Comment by takluyver** [comment]
If a non-empty dummy key works, let's go with that.

**Comment by rkern** [comment]
Great, PR landing shortly.
