### ISSUE TITLE
Make kernel be quiet about Ctrl-C when --quiet option is passed?

### ISSUE THREAD

**Issue by gibiansky** [ipython/ipykernel#166]
I have a use-case when I am starting a kernel programmatically, and thus get the Ctrl-C message. 

I see that if I provide the parent PID in the `JPY_PARENT_PID` environment variable, the message isn't printed; but I don't have easy access to the parent PID so I would prefer for it to just be quiet. 

a) Is there a reason that I _should_ pass JPY_PARENT_PID, that the kernel uses for any good reason?
b) If not, could the `--quiet` option be checked [here](https://github.com/ipython/ipykernel/blob/6035f9eaf561383ae7b78b9125dec235ac8c7810/ipykernel/kernelapp.py#L291) to prevent the kernel from printing the Ctrl-C message if it's set?

**Comment by minrk** [comment]
JPY_PARENT_PID is used so that the kernel will shut itself down if the process with that PID goes away. It's generally used to signal "Somebody started me, I shouldn't stick around if they are gone". The corollary is used for this `io.rprint`, in which the kernel guesses that it was started by hand with `ipython kernel` if this isn't specified, in which case it shows an extra message to the probable human at the terminal.

We can definitely check the log-level so that it's not printed if `--quiet` is given (#168), but I'm guessing it would be a good thing to pass JPY_PARENT_PID for any process that's spawning kernels, unless those kernels should survive longer than their parent.

**Comment by gibiansky** [comment]
Got it, thanks!
