### ISSUE TITLE
Tests hang on exit

### ISSUE THREAD

**Issue by takluyver** [ipython/ipykernel#207]
@minrk I'm trying to debug this failure on Jenkins. I recall you saying it was probably related to threads failing to exit. So far I can reproduce it by manually running:

```
PYTHONHASHSEED=6 nosetests -v ipykernel
```

I don't see it running a specific part of the tests, only running the whole test suite. I can remove some test files and still get the hang, but there are several files where if I remove any of them I 
no longer see the hang.

**Comment by minrk** [comment]
Thanks, I'll try to dig into it.

**Comment by takluyver** [comment]
My last attempt before I wrapped up for the day was an atexit handler to
show which threads were still active. I got a traceback from inside the
threading module.

**Comment by infinity0** [comment]
@takluyver Hi Thomas, long time no see!

> there are several files where if I remove any of them I no longer see the hang.

Could you tell us which ones they are? This has been marked as a [release-critical bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849220) for the Debian package and currently our plan is to disable the tests. However I'd rather disable parts of the suite rather than the whole suite.

**Comment by takluyver** [comment]
Sorry, got distracted onto other things. I'll try to get back to this, but unfortunately, I cannot remember which specific files I was referring to. It was not a set that had any obvious common factor.
