### ISSUE TITLE
Unable to pickle.load(fig) with mpl in jupyter notebook

### ISSUE THREAD

**Issue by cbyrohl** [ipython/ipykernel#231]
I use the following code snippet on Py35/matplotlib2.0.0//ipykernel 4.5.2 installed via Anaconda3:

```python
import matplotlib.pyplot as plt
import numpy as np
import pickle



ax = plt.subplot(111)
x = np.linspace(0, 10)
y = np.exp(x)
plt.plot(x, y)
with open('bla.pickle', 'wb') as pickle_file:
    pickle.dump(ax, pickle_file)
import matplotlib.pyplot as plt
import pickle

with open('bla.pickle', 'rb') as pickle_file:
    ax = pickle.load(pickle_file)
plt.show()
```

The latter pickle.load() fails with:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-0e84ab5169e3> in <module>()
     15 
     16 with open('bla.pickle', 'rb') as pickle_file:
---> 17     ax = pickle.load(pickle_file)
     18 plt.show()

/home/uni09/cosmo/cbyrohl/anaconda3/envs/py35/lib/python3.5/site-packages/matplotlib/figure.py in __setstate__(self, state)
   1443             allnums = plt.get_fignums()
   1444             num = max(allnums) + 1 if allnums else 1
-> 1445             mgr = plt._backend_mod.new_figure_manager_given_figure(num, self)
   1446 
   1447             # XXX The following is a copy and paste from pyplot. Consider

AttributeError: module 'ipykernel.pylab.backend_inline' has no attribute 'new_figure_manager_given_figure'
```

This code was executed in a jupyter notebook (ipython 5.3).

When executing as usual python script, it works just fine. It also works fine when dumping in Jupyter and loading in script.

**Comment by mrclary** [comment]
I observe the same behavior for Jupyter's `console/qtconsole/notebook`.
However, I have been successful at pickling and unpickling figures in IPython and `qtconsole`, provided that the session is started with a non-inline backend; the interactive state does not matter.

## Observations
I've made the following observations regarding pickling figures in inline sessions.
* Attempting to open a pickled figure, which is known to be good, results in the following error:
```python
/Users/rclary/anaconda/lib/python3.5/site-packages/matplotlib/figure.py in __setstate__(self, state)
   1443             allnums = plt.get_fignums()
   1444             num = max(allnums) + 1 if allnums else 1
-> 1445             mgr = plt._backend_mod.new_figure_manager_given_figure(num, self)
   1446 
   1447             # XXX The following is a copy and paste from pyplot. Consider

AttributeError: module 'ipykernel.pylab.backend_inline' has no attribute 'new_figure_manager_given_figure'
```

* Attempting to pickle a figure succeeds only if the interactive state is false and `plt.show()` has NOT been called. The pickling executes without error, but the figure is not retrievable. Attempting to unpickle in a non-inline session does not yield a viewable figure and attempting to save the figure (to pdf, for instance) reveals an issue with the figure canvas (why?)
```python
/Users/rclary/anaconda/lib/python3.5/site-packages/matplotlib/figure.py in savefig(self, *args, **kwargs)
   1570             self.set_frameon(frameon)
   1571 
-> 1572         self.canvas.print_figure(*args, **kwargs)
   1573 
   1574         if frameon:

AttributeError: 'NoneType' object has no attribute 'print_figure'
```

## Testing
Starting an IPython session from my terminal creates a session with 'MacOSX' backend. This permits successful pickling and unpickling of figures.
<pre>$ ipython </pre>
In this session I run the following code:
```ipython
In [1]: import pickle as pkl
   ...: import matplotlib.pyplot as plt
   ...: 

In [2]: plt.interactive(True)

In [3]: fig = plt.figure()

In [4]: plt.plot(range(10))
Out[4]: [<matplotlib.lines.Line2D at 0x11f4bd5f8>]

In [5]: with open('fig_good.pkl', 'wb') as f:
   ...:     pkl.dump(fig, f)
   ...:     

In [6]: with open('fig_good.pkl', 'rb') as f:
   ...:     fig2 = pkl.load(f)
   ...:     
```
This gives me two figures, the first one created in the session, the other loaded from the pickle file. Both are viewed in separate windows (MacOSX backend) and are interactive.

I used the `fig_good.pkl` to test unpickling inside inline sessions. I used this IPython session to verify the results of figures pickled from inline sessions.

## Conclusions
* Inline sessions **cannot** unpickle figures because the inline module does not have the appropriate attribute (see errors above)
* Inline sessions **can** pickle figures, but only under the strict conditions that the interactive state is false and that `plt.show()` has not been called in the session. I can offer no explanation for this behavior.

**Comment by mrclary** [comment]
@cbyrohl , I found the solution...
As we both noted, the error lies in that the inline backend doesn't have a `new_figure_manager_given_figure` attribute. I circumvent this issue by switching backends using `%matplotlib notebook` at the beginning of the notebook. I suspect that there may be issues trying to switch backends in the middle of a notebook (https://github.com/jupyter/notebook/issues/473) but I haven't explored that.

The following code works in a Jupyter 4.3.0 notebook and Matplotlib 2.0

```python
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
import pickle

ax = plt.subplot(111)
x = np.linspace(0, 10)
y = np.exp(x)
plt.plot(x, y)
with open('bla.pickle', 'wb') as pickle_file:
    pickle.dump(ax, pickle_file)
import matplotlib.pyplot as plt
import pickle

with open('bla.pickle', 'rb') as pickle_file:
    ax = pickle.load(pickle_file)
```

**Comment by cbyrohl** [comment]
@mrclary Great, just checked and this seems to be a good workaround for now. Thanks!

**Comment by abast** [comment]
The workaround displays the figures, that are unpickled ... is there any way to suppress that?

**Comment by mrclary** [comment]
@abast,  
It is possible to suppress the display of the figure loaded from a pickle file by using the rcparameter `interactive=False`. This is works to suppress display of any figure, not just for those loaded from pickle files. In the following, I've put the rcparameter in a context manager so that it only affects the figure loaded from the pickle file and not the rest of the notebook.

```python
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
import pickle

ax = plt.subplot(111)
x = np.linspace(0, 10)
y = np.exp(x)
plt.plot(x, y)
with open('bla.pickle', 'wb') as pickle_file:
    pickle.dump(ax, pickle_file)

with open('bla.pickle', 'rb') as pickle_file, plt.rc_context(rc={'interactive': False}):
    ax = pickle.load(pickle_file)
```

**Comment by mrclary** [comment]
@abast,  
Hmm... I don't know why it wouldn't work for you. It definitely works for me; I'm running Jupyter 4.4.0 and Matplotlib 2.2.2 on Mac OSX 10.13.6
