### ISSUE TITLE
Move overiding matplotlib RC to using a theme. 

### ISSUE THREAD

**Issue by Carreau** [ipython/ipykernel#267]
Right now we override matplotlib parameters when using inline: 

https://github.com/ipython/ipykernel/blob/29abbedcd0ed09ceb7ea5a179cae767f8df91e8f/ipykernel/pylab/config.py#L45-L59

We can do better now that matplotlib have styles; It wil have 2 advantages: 
1) let users changes the parameter we override (https://github.com/matplotlib/matplotlib/issues/9217#issuecomment-331511669)
2) let users export figures using savefig with the __same__ parameters than the inline plot.

**Comment by mgeier** [comment]
Is there any news on this?

Is there a way to have different presets (or "styles"?) for (kernels started by) the Qt Console and for (kernels started by) the Notebook?

I've also tried to get some information from the mailing list, but I didn't get a response:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/jupyter/nSVmAsbaLnk

I've found out that the most meaningful `figure.dpi` setting for the Notebook is 96, while the current value of 72 seems best for Qt Console.

BTW, I also don't think it makes sense (anymore?) to change the default `figure.figsize`.
I'm not sure about the colors ...

I've made a notebook with a suggestion for an intermediate work-around: http://nbviewer.jupyter.org/github/mgeier/python-audio/blob/master/plotting/matplotlib-inline-defaults.ipynb

But it would be great if that could be fixed in IPython itself!

Here is an example that shows that plots using SVG and PNG with a setting of 96 DPI have about the same size:

https://nbsphinx.readthedocs.io/en/latest/code-cells.html#Plots

Here you can see the same thing for PDF and PNG plots when converted to LaTeX/PDF:

https://media.readthedocs.org/pdf/nbsphinx/latest/nbsphinx.pdf#subsubsection.4.3.4

**Comment by mangecoeur** [comment]
+1 to resolving this: at the moment you get the weird behavior that if you do `%matplotlib inline` and `plt.rcParams['figure.dpi'] = 100` in the same cell, the manual dpi setting gets overridden, but if you do them in separate cells it doesn't. Which is bananas,

**Comment by dlukes** [comment]
I'd love to help with this -- I teach Python to beginners using Jupyter Notebook / JupyterLab, and using matplotlib is always a stumbling block. Interactive plots are finicky to set up and use, and inline ones are too small by default, so they require fiddling with rcParams, which isn't beginner friendly either.

However, having downloaded the code and played around with it to figure out how it works, I'm **not sure how switching to matplotlib styles is supposed to help**, as claimed in OP:

> We can do better now that matplotlib have styles; It wil have 2 advantages:
> 1. let users changes the parameter we override (matplotlib/matplotlib#9217 (comment))

If the hypothetical inline style sets `figure.dpi` to 72, then the effect will be exactly the same as the current code directly manipulating rcParams, the new value will just override any previously set value. Which means that setting a higher `figure.dpi` in `matplotlibrc` will still have no tangible effect, which is what matplotlib/matplotlib#9217 was originally complaining about.

Here's a quick demo showing that switching styles can still override previously set `figure.dpi`:

```python
In [1]: import matplotlib as mpl                                                                                                                                                                                                               
In [2]: import matplotlib.pyplot as plt                                                                                                                                                                                                        
In [3]: mpl.rc("figure", dpi=150)                                                                                                                                                                                                              
In [4]: mpl.rcParams["figure.dpi"]                                                                                                                                                                                                             
Out[4]: 150.0
In [5]: plt.style.use("classic")
In [6]: mpl.rcParams["figure.dpi"]                                                                                                                                                                                                             
Out[6]: 80.0
```

So again, not sure how using styles to set inline rcParams would enable users to set a preferred `figure.dpi` via `matplotlibrc`. Or maybe I misunderstood the suggestion? If so, please clarify, I'd really like to help with this :)

**Comment by dlukes** [comment]
Slightly unrelated, for future reference -- this is where the inline rcParams actually get loaded by IPython:

https://github.com/ipython/ipython/blob/8971c8e5f31d20768609e20f60870d627eb33bd0/IPython/core/pylabtools.py#L394-L395

**Comment by danieloliveira56** [comment]
I believe this commit to `matplotlib-inline` fixed this issue:
https://github.com/ipython/matplotlib-inline/commit/a433a899280c9cf801ccb5eb99faa1e15fc8a459

**Comment by fperez** [comment]
Thx for flagging that @danieloliveira56 - and FYI for all, that commit is now in the current 0.1.6 release of mpl-inline. So an update to that package might be enough to close this issue, I think.

**Comment by fperez** [comment]
This is old and I think solved, closing for now, please reopen if there's actually new actionable info.

**Comment by dlukes** [comment]
Fixed indeed, thank you very much!

![image](https://user-images.githubusercontent.com/2734517/188473291-9fb66f62-6e77-4c49-bfcb-157039cd2c7d.png)
