### ISSUE TITLE
Figures won't be rendered if importing matplotlib.pyplot and calling pyplot.show at the same cell.

### ISSUE THREAD

**Issue by hirokiky** [ipython/ipykernel#292]
Hi.

I met some problem with Jupyter Notebook and matplotlib.pyplot
and found the issue caused by `ipykernel`.

## Problem

If we import `matplotlib.pyplot as plt` and calling `plt.show()` on a same cell,
then any graphs won't be rendered.

See this tiny Gist
https://gist.github.com/hirokiky/cf2e63bb8a08291523056bb248abd764

## Happening on 4.7.0 or later

I tried this quick checking with `ipykernel==4.7.0` and master branch of thin repository.
This issue didn't appear with `ipykernel==4.6.1`.

Here's my environment.

```
python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': 'ca5443062',
 'commit_source': 'installation',
 'default_encoding': 'utf8',
 'ipython_path': '/private/tmp/demoplot/venv/lib/python3.6/site-packages/IPython',
 'ipython_version': '6.2.1',
 'os_name': 'posix',
 'platform': 'Darwin-16.4.0-x86_64-i386-64bit',
 'sys_executable': '/private/tmp/demoplot/venv/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) \n'
                '[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]'}
```

This is originally reported by my friend @SaitoTsutomu.

(Is this correct way to report or correct repository?)

**Comment by Carreau** [comment]
I believe this is expected and relatively hard to do better. 
The reasoning is that IPython need to do some setup before being able to plot inline; we do our best to detect when matplotlib has been imported and set that up automatically (equivalent of calling `%matplotlib inline`. The issue is all need to be setup before you try to plot the first figure. Unfortunately we can only detect matplotlib import after the first cell has been ran. 

As you discovered one  way to do so is to import matplotlib in a different cell; call `%matplotlib inline`, or set matplotlib inline in your ipykernel config file before plotting for the first time.

It might be possible to fix this behavior but it might be tough.

**Comment by hirokiky** [comment]
@Carreau I see. Thanks for your reply.
I'll use `%matplotlib inline` in my case and close this issue (if you think it's important, please re-open it).
I wish you a happy new year.
