### ISSUE TITLE
Cannot run code that wants to start an asyncio loop

### ISSUE THREAD

**Issue by bfredl** [ipython/ipykernel#372]
I have been able to use a library inside an ipython session before, that starts an asyncio event loop. Now as ipykernel runs an asyncio event loop itself, this fails with the error:

    RuntimeError: Cannot run the event loop while another loop is running

Is it possible to revert to the old behavior of not running cells inside asyncio? I expected `%autoawait False` to do this, but nope. Grepping the options I though I found the relevant option:
```
c.InteractiveShell.loop_runner = 'IPython.core.interactiveshell._pseudo_sync_runner'
c.ZmQInteractiveShell.loop_runner = 'IPython.core.interactiveshell._pseudo_sync_runner'
```
but, no, this doesn't work either. Neither does `%gui tk` or something like that. Can the event loop be turned off? Must someone implement `IPython.core.interactiveshell._real_sync_runner` for this to work?

**Comment by minrk** [comment]
ipykernel uses tornado which uses asyncio by default in 5.0, so this isn't possible with current or future versions of tornado. asyncio is always running in an IPython kernel. In the short-term, you can force tornado<5, but going forward the asyncio eventloop will be running.

Can you point to the library that requires starting the asyncio eventloop in the main thread itself? This would mean that the library can never be used in an asyncio application, in IPython or elsewhere.

**Comment by minrk** [comment]
Never is indeed a strong word, sorry about that. I mainly mean that an API that unconditionally initializes and runs the main loop cannot be used in any asyncio application without being assigned to its own thread. This is because the asyncio loop is a per-thread signleton, unlike tornado pre-5, where you could have many IOLoop objects and it's fine for each library to own and operate its own loop. So any call to `run_until_complete` or similar is making the assumption that asyncio isn't used in the calling context.

If an api is built on asyncio, the way I'd go is to have a mostly async api with a thin `asyncio.get_event_loop().run_until_complete(async_api())` blocking wrapper.

If the library does indeed want to always run its own asyncio eventloop to implement a blocking api, it can do this safely by creating a thread in which to run. That way, it would never conflict with the asyncio loop that may or may not be running in the calling thread. IPython parallel is an example of such a library, which runs an asyncio (via tornado) eventloop in a background thread and provides a blocking api in the calling thread.

**Comment by bfredl** [comment]
> If an api is built on asyncio, the way I'd go is to have a mostly async api with a thin asyncio.get_event_loop().run_until_complete(async_api()) blocking wrapper.

That was what I was trying to allude to. We can keep the sync API that works unconditionally across python versions, but also have a python3.5+ API for newer plugins/clients that want to integrate with other asyncio libraries.

Probably we can avoid spawning a separate thread though. when `pynvim` acts as a plugin host, it owns the main thread anyway, and when used as a library we should provide separate interfaces that work effectively in each case.
