### ISSUE TITLE
Successfully executed cells get stuck in busy state until notebook finishes its run

### ISSUE THREAD

**Issue by stas00** [ipython/ipykernel#389]
There is a long issue thread at jupyter-notebook https://github.com/jupyter/notebook/issues/4334, where I thought originally the problem was coming from, but eventually got it traced down to this commit that broke it: https://github.com/ipython/ipykernel/commit/3b1f632528e3577539e96340f9d751723bf5c7cc
```
3b1f632528e3577539e96340f9d751723bf5c7cc is the first bad commit
commit 3b1f632528e3577539e96340f9d751723bf5c7cc
Author: Min RK <benjaminrk@gmail.com>
Date:   Wed Sep 5 13:53:27 2018 +0200

    use PriorityQueue for messages

    ensures control messages maintain priority

:040000 040000 28a56cc56df07170b7a939c5fad721f116c06af0 3f56c2b17276897e406107919ae57d7d9b3f7a3f M      ipykernel
```

Problem description:

With Run All the cells run and clear the busy status just fine and then at some cell down the road successfully executed cells start showing as busy `[*]`. It seems to appear in random places in different notebooks, usually in the exact same code cell of a given notebook, regardless of the content. Here is a snapshot from 'Run All':

![screenshot_8](https://user-images.githubusercontent.com/10676103/50939418-a1ae0480-1431-11e9-82e1-eaf544e5f7db.png)

I succeeded at creating a simple test case (had to rename it to .txt to be able to upload, please rename it to .ipynb to try).
[stuck.txt](https://github.com/jupyter/notebook/files/2743186/stuck.txt)

**You can reproduce this problem by running it live in one click here:**
https://mybinder.org/v2/gh/stas00/fastai-misc/master?filepath=debug%2Fjupyter%2Fstuck.ipynb

Please let me know if you'd like to me to re-copy the debug and tracing details - there is so much to copy, as it spans several posts.

This problem impacts many of us, in particular extensions that rely on not having this bug.

**Comment by stas00** [comment]
@minrk, since it was your commit that according to `git bisect` resulted in this issue, perhaps you could kindly have a look at it? Thank you!

**Comment by minrk** [comment]
Thanks for all your effort tracking this down! Indeed, it's probably something preventing the delivery of a message, which we attempt to ensure with `.flush()`, but may not be doing correctly. As indicated, the `execute_reply` message is being delayed somehow. That's what we want to track down the root cause of.

I think the bisect is not finding the right commit, though perhaps that one made it more likely, as an earlier report of the same issue (https://github.com/jupyter/notebook/issues/2748 ) predates that commit by a year and a bit.

This *should* purely be a UI concern, not a computational one: The UI is suggesting that some cells are busy, even after they complete and their results are delivered and displayed.

**Comment by minrk** [comment]
I was able to reproduce it locally with your notebook and #390 fixes it for me. Can you verify the fix?

**Comment by stas00** [comment]
That fixes it indeed - thank you, @minrk!
