### ISSUE TITLE
Master build failures with Python 3.7

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipykernel#645]
There may have been some new PyPI release of our dependencies causing these failures.

```
argcomplete 1.12.2 has requirement importlib-metadata<4,>=0.23; python_version == "3.7", but you have importlib-metadata 4.0.1.
```

**Comment by ltalirz** [comment]
Hi @SylvainCorlay  , since we need importlib-metadata >=4,  this fix forced us to use an earlier version of ipykernel.

I just wanted to point out that the latest v1.12.3 patch release of argcomplete has bumped the importlib-metadata upper limit to <5:
https://github.com/kislyuk/argcomplete/blob/develop/setup.py#L8

I'll open a PR to bump this
