### ISSUE TITLE
Dropping the dependency to tornado

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipykernel#656]
We are not using the tornado coroutines anymore in the codebase (since #632) which also fixed some issue with respect to context variables. I think that it would make sense to drop tornado completely at some point.

I am opening this issue to track the work required for this, as it may require significant work in the codebase:

 - switching the asyncio API of pyzmq.
 - asyncio enforces stronger constraints about instanciating queues and loops in the thread where they are run.

**Comment by minrk** [comment]
Adding a note that this is not a pressing issue - since we use tornado as very little more than an asyncio runner, we might as well run asyncio directly, but there is no real cost to continue using tornado as the runner at this point. It's fine to remove things piecemeal (native coroutines done, asyncio Queues next, etc.), but indeed the switch to `zmq.asyncio` will be the biggest change.

This is technically a user-facing change, in that anyone calling `IOLoop.current()` will no longer have access to a running loop, but I'm not sure anyone is actually doing that.

**Comment by SylvainCorlay** [comment]
Absolutely. I opened the issue because I can't tackle that right now, however, it would be a nice thing to do in the future.
