### ISSUE TITLE
IPKernelApp configs capture_fd_output and quiet conflict and break ipykernel

### ISSUE THREAD

**Issue by MrBago** [ipython/ipykernel#859]
When `c.IPKernelApp.capture_fd_output` is True (default True) and `c.IPKernelApp.quiet` if False (default True), printing anything causes an infinite output in the cell. `quiet = True` causes outputs to get directed to fd, which then gets picked up by the `capture_fd_output` logic and re-printed. This loop continues until the process is killed.

**Comment by jasongrout-db** [comment]
Adding context to link PRs together: the infinite output seems to have started in the initial commit of https://github.com/ipython/ipykernel/pull/630, and the `capture_fd_output` was introduced in #752.

**Comment by garlandz-db** [comment]
More specifically, when `capture_fd_output=True` and `quiet=False`, we echo the text back to sys.__stdout__ which was  overwritten (in addition to sys.stdout) since we change the underlying file descriptor. Therefore we are echoing text by writing it back to the pipe instead of the terminal. So the watcher thread then reads that same text again in the pipe, writes to the terminal and then echos. reads, writes to terminal, echos.

Not that this is a solution but setting echo=None prevents the infinite loop

**Comment by garlandz-db** [comment]
One proposal for solution: in the case that quiet=False, capture=True, the watcher threads are only able to send zmq messages. That is, directly calling `write()` like `sys.stdout.write()` would actually echo the data onto the stdout pipe, which will then be picked up by the watcher thread and then write to zmq but this time with echo disabled. 
![image](https://user-images.githubusercontent.com/110427462/229599681-c1d3e959-a494-4989-884e-c7410cfa45b3.png)

appreciate any feedback!

**Comment by garlandz-db** [comment]
another solution alternative. 

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/110427462/230421908-eaee1e10-4361-45fb-a326-acd0bd4caad8.png">

**Comment by Zsailer** [comment]
Hi @Carreau or @minrk, do you mind taking a look at these proposed solutions?

**Comment by Carreau** [comment]
I haven't touched this file in a long time, and it's complicated enough that I don't think I can properly judge this. 

In general I believe the watcher thread is complex, and a real fix that would fix this and other things,  would be to really implement the kernel nanny. 

The kernel nanny have a real way to actually capture output, and would allow to process signals, and metrics without having to worry about the kernel being stuck in a compiled library.

**Comment by garlandz-db** [comment]
How much effort would it take to implement the kernel nanny? This also seems non-trivial and would probably require a major release to ship.

**Comment by jasongrout-db** [comment]
For context:
* [previous discussion from years ago about a kernel nanny](https://github.com/jupyter/enhancement-proposals/pull/14)
* [some experiements implementing kernel management things like a nanny](https://github.com/takluyver/jupyter_kernel_mgmt)

**Comment by Carreau** [comment]
Another experiment; https://github.com/carreau/inplace_restarter, this intercept commands and when it see "%restart" just restart the subprocess. 

It's not hard to implement, it's just the occasion to update the jupyter protocol and document it.

Technically we can implement it in a completely transparent manner, but I believe it would be nice to agree on a way to tell the kernel "you are under nanny" supervision, you do not need to do X, Y, Z. It would also be a good way to implement the handshake protocol, as the nany could do the handshake transparently for older kernels.

**Comment by garlandz-db** [comment]
@Carreau thanks for your insight! im not too sure how long the process to shipping new code in ipykernel takes. if you had to give an estimate, how long would the kernel nanny take to be shipped in ipykernel? it also seems determining the handshake pattern is a blocker then to implementing the nanny (using handshake protocol) since that JEP is still in discussion.

**Comment by Carreau** [comment]
The longest will be implementing it. Making a new release assuming purely nanny that does not change the protocol should not be long. We can even make it opt-in or in beta state. The hard thing is finding time to write the code.

**Comment by minrk** [comment]
While I still think the nanny is a good idea (I ended up implementing a version of it [in ipython parallel](https://github.com/ipython/ipyparallel/blob/main/ipyparallel/engine/nanny.py), though notably it does not include output capture), I think this specific self-looping issue can be solved in a much smaller way, since we [already have a solution for that for the logger](https://github.com/ipython/ipykernel/blob/756c588df92cab0adddecdfae63e019540f62331/ipykernel/kernelapp.py#L475-L483). We can do the same thing for the echo and solve this specific bug (i.e. echo FD should be `_original_stdstream_copy`, not `__stdout__`)

**Comment by garlandz-db** [comment]
@minrk  just to double check my understanding, is this mental model correct that we are going from
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/110427462/233714225-ca37dfce-3b3a-42aa-94c1-147393639a16.png">


to this (aka move the arrow to the terminal output):

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/110427462/233713998-41482c08-3ffe-4d54-bd2f-0663ee0f9192.png">

**Comment by minrk** [comment]
Yes, I think that's right. I believe #1111 fixes this, but I haven't quite got the tests to not mess with pytest's output capture.

**Comment by garlandz-db** [comment]
can confirm this fix works as expected. i copied your line change and the loop issue is gone. thanks for doing this @minrk!! lmk if there is something i can help with to drive this to completion
